#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Initialize local settings files
init_settings ()
{
	# Copy from settings templates
	rm -Rf ${SITEDIR_PATH}/settings.php
	copy_settings_file "${SITEDIR_PATH}/default.settings.php" "${SITEDIR_PATH}/settings.php"
}

# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
}

# Install site
site_install ()
{
	cd $DOCROOT_PATH

	# We disable email sending here so site-install does not return an error
	PHP_OPTIONS="-d sendmail_path=`which true`" drupal site:install standard \
			--langcode="en"  \
			--db-type="mysql"  \
			--db-host="db"  \
			--db-name="default" \
			--db-user="root"  \
			--db-pass="root"  \
			--db-port="3306"  \
			--db-prefix="d8_"  \
			--site-name="Drupal 8"  \
			--site-mail="admin@example.com"  \
			--account-name="admin"  \
			--account-mail="admin@example.com"  \
			--force
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
fix_permissions
init_settings
time site_install

#-------------------------- END: Execution --------------------------------
