version: '2'

networks:
  enifront:
    driver: bridge

services:
  selhub:  
    image: selenium/hub
    environment:
     - GRID_TIMEOUT=200000
     - GRID_BROWSER_TIMEOUT=200000
    ports:
      - "4444:4444"
    networks:
      - enifront

  nodeff:  
    image: selenium/node-firefox-debug
    ports:
      - "5900"
    networks:
      - enifront
    volumes:
      - /dev/urandom:/dev/random
    depends_on:
      - selhub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selhub
      - HUB_PORT_4444_TCP_PORT=4444

  nodechrome:  
    image: selenium/node-chrome-debug
    ports:
      - "5900"
    volumes:
      - /dev/urandom:/dev/random
    networks:
      - enifront
    depends_on:
      - selhub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selhub
      - HUB_PORT_4444_TCP_PORT=4444