www:
  restart: always
  build: containers/nginx
  hostname: nginx.drupal.dev
  container_name: d8_dev_env_web
  ports:
   - "80:80"
  links:
   - php
  volumes:
   - ../../../../public_html:/var/www/public_html
php:
  restart: always
  build: containers/php
  hostname: php.drupal.dev
  container_name: d8_dev_env_php
  ports:
   - "9000:9000"
  links:
   - mysql
  volumes:
   - ../../../../public_html:/var/www/public_html
mysql:
  restart: always
  image: mysql:5.7
  container_name: d8_dev_env_mysql
  hostname: nginx.drupal.dev
  ports:
   - "3306:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=drupal
   - MYSQL_USER=drupal
   - MYSQL_PASSWORD=drupal
